### ISSUE TITLE
Interoperability with Tab Modifier extension

### ISSUE THREAD

**Issue by chuckhopkins** [willg101/blue-dot-replacement#3]
I was able to successfully configure your [Blue Dot Replacement](https://chrome.google.com/webstore/detail/blue-dot-replacement/opjidajjikdcpbpbbcmadmignnimecco) extension in Chrome (with Chrome's default tab icons).  

However, as soon as I activated another Chrome extension ([Tab Modifier](https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai)) to change the default tab icons, I cannot get your extension to work anymore.  

Do you know if there is anything I can do to get the 2 extensions to work together?

Thanks,
Chuck

**Comment by willg101** [comment]
Hi Chuck  - would you be willing to share the config you used for the Blue Dot Replacement (BDR), as well as Tab Modifier?

In particular, for the tab that BDR did not work for, were any Tab Modifer rules active that were related to title or icon?

**Comment by chuckhopkins** [comment]
Hi Will - 

When I install BDR with the default config, it works.  Any time a tab changes, the tab icon flashes between the default icon for that site and the yellow alarm bell that is the default for BDR.  I've also successfully configured BDR with a different icon that flashes as well.

However, when I install Tab Modifier, and configure a URL (gmail for instance), it successfully changes that tab to the custom icon I configured.  However, then BDR no longer flashes between the yellow alarm bell and the custom icon.  

Does that help?  Any other config info you need?

Thanks,
Chuck

**Comment by willg101** [comment]
Perfect - thanks.

Unfortunately, after looking at Tab Modifier's code, I do not believe these two extensions are compatible for your use case. To ensure that the custom icon you select within Tab Modifier is always showing, [Tab Modifier watches for any changes to a tab's icon and immediately overrides the change with your custom icon](https://github.com/sylouuu/chrome-tab-modifier/blob/master/dist/js/content.js#L222). This means that as soon as BDR changes a tab's icon to the bell, Tab Modifier reverts the icon before you see the bell.

For clarify, __there is nothing wrong with Tab Modifier's implementation__, but it does mean that no other extension is able to change a tab's icon once Tab Modifer has altered that tab's icon.
