### ISSUE TITLE
Notification icon not clearing once tab has focus

### ISSUE THREAD

**Issue by RallyChris** [willg101/blue-dot-replacement#4]
Use to work fine, so suspect it's a chromium update that has changed something.  But the notification doesn't go away when the tab gets focus.  Only able to clear it with a refresh of the tab.

Using brave browser which is chromium based

Brave is up to date
Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Comment by willg101** [comment]
Thanks! I'll look into this today or tomorrow.

**Comment by tayomoore** [comment]
I am also seeing this as of today

**Comment by willg101** [comment]
This appears to be Brave-specific, as I can reproduce this in Brave, but not in Chrome or plain Chromium 91.

I'll need to investigate what's different with how Brave works with extensions.

**Comment by tayomoore** [comment]
I'm on mainline Chrome (Version 91.0.4472.77 (Official Build) (64-bit)) and also experiencing it. Is there anything I can do to help diagnose?

**Comment by willg101** [comment]
Oh, interesting. I am on Windows 10; are any of you using macOS or Linux?

**Comment by tayomoore** [comment]
Nope, I'm Windows 10 too

**Comment by tayomoore** [comment]
For me, it's not happening all the time, about 10% of the time it works. If it helps, in my case, I have a pinned tab for my gmail, and it's on that one that it's not working most of the time. I have the ext enabled on pinned tabs only and set not to flash.

**Comment by willg101** [comment]
I was finally able to reproduce it tonight on mainline Chrome. After digging into the logs, I found an error that lead me to this SO thread: https://stackoverflow.com/questions/67806779/im-getting-an-error-tabs-cannot-be-edited-right-now-user-may-be-dragging-a-ta.

It appears to be a browser bug, but a workaround is provided in that thread that I will attempt to apply.

**Comment by willg101** [comment]
I have submitted an update to the Chrome Web Store.

**Comment by willg101** [comment]
OK - this latest version is live on the Chrome Web Store.
